# --- SITE INFORMATION AND META DATA --- #
baseURL: "https://thelabdigital.github.io/"
languageCode: "en-us"
title: "Sithu Aung"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 3

enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-EY3KH0WZKV

markup:
  goldmark:
    renderer:
      unsafe: true

# --- MAIN MENU ITEMS (EXPECT FROM ANCHOR POINT ON LANDING PAGE) --- #
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

params:
  title: "Sithu Aung"
  description: My Porfolio and blog
  favicon: "/fav.png"
  useBootstrapCDN: false
  mathjax: false
  animate: true
  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark
  font:
    fontSize: 1.15rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Sithu Aung" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Sithu Aung."
    subtitle: "I develop strategies, making yours simply work!"
    content: "Hi there! Your friendly neighborhood marketing strategist, analyst, consultant, research enthusiast, and—let's face it—a full-on strategy aficionado is here!"
    image: /images/me_hero_1.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Download My Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-square-facebook
          url: https://www.facebook.com/sithu.aung.leo
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/sithuaung88/
        - icon: fab fa-github
          url: https://github.com/SithuAung1988

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me_hero_2.jpg"
    content: |-
              I'm a strategic marketing professional from Myanmar with a solid background in media, marketing, communication, and advertising. I began my career at 19 in Dubai's hospitality industry, transitioned to Myanmar's print media sector in 2010, and by 2016 was developing digital and social media strategies at "Ogilvy Myanmar". Later, I became "Head of Digital Sales and Marketing" at "The Irrawaddy Media", one of Myanmar's leading digital media outlets, and co-founded "The Lab Digital", an agency supporting local MSMEs and NGOs. I've also worked as a Consultant and freelanced for organizations of all sizes, including "Hogarth Worldwide", "ICAP at Columbia University", and "Institute for Strategy and Policy-Myanmar".

              Outside of work, I'm a reader, writer, blogger and online educator, teaching classes via Zoom on topics like business strategy, marketing, dataanalytics, and operational research to inspire Myanmar's next generation of marketers. In my free time, I enjoy coding for fun (Python, PHP, R, and SQL, if you're curious), exploring Buddhist ethics in business strategies, and geeking out on Indian/Hindu astrology. (Check out my GitHub to learn more about my Python project on Hindu astrology.) I'm also a lifelong Manchester United fan and a proud cat parent.

              Currently, I'm focused on enhancing my skills in developing and optimizing strategies, consumer behavior and marketing, and data analytics, AI in marketing, and business ethics. If you're looking for someone versatile, adaptable, and ready to make an impact, let's connect!
    skills:
      enable: true
      title: "Here are a few of the topics I'm currently working on:"
      items:
            - Strategy Development and Consultation
            - Marketing and Communication Campaigns
            - Performance Monitoring, Evaluation, and Optimization
            - Research and Data Analytics
            - Content Creation
            - Training

            # - Strategy Development and Consultation - including market entry strategies  
            # - Planning and Execution of Marketing and Communication Campaigns  
            # - Data Collection, Statistical Analysis, Data Interpretation, and Presentation  
            # - Development of Business Plans, Marketing Plans, Campaign Plans, and Project Proposals  
            # - Content Strategy, Content Creation, Copywriting, Translation, and Editing  
            # - Research and Training in Marketing  

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
##### - Job #01 - #####
      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |-
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.
##### - Job #02 - #####
      - job: "Assistant Digital Planner"
        company: "Ogilvy Myanmar"
        companyUrl: "https://www.todayogilvy.com/"
        date: "Feb 2016 - Dec 2021"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |-
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

# Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      # --- MASTER DEGREE --- #
      - title: "Master of Marketing Management"
        school:
          name: "University of Economics, Monywa"
          url: "https://mue.edu.mm/"
        date: "2024 - Present"
        GPA: false
        content: |-
          Remark:
            - Right now, I'm enrolled in an online master's program in Marketing Management at the University of Economics, Monywa.
      # --- BACHELOR DEGREE --- #
      - title: "Bachelor of Business Management"
        school:
          name: "University of Distance Education, Yangon"
          url: "https://www.yude.edu.mm/"
        date: "2006 - 2024"
        GPA: false
        content: |-
          Remark:
          - I dropped out of university back in 2008 and headed abroad to work.
          - Fast forward to 2022, I decided to jump back in and finish what I started. By 2024, I finally earned my degree!
      # --- HIGH SCHOOL --- #
      - title: "High School"
        school:
          name: "Basic Education High School No. 6 Botataung, Yangon"
          url: "https://en.wikipedia.org/wiki/Basic_Education_High_School_No._6_Botataung"
        date: "1998 - 2004"
        content: |-

          - Yes, I'm a proud alumnus of St. Paul's English High School.
  
  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: Google Advanced Data Analytics
        content: May 16, 2023
        url: https://coursera.org/verify/professional-cert/CPLUU9C2Y3E4
        image: /images/cert/gada.png
      - title: Google Business Intelligence
        content: May 17, 2023
        url: https://coursera.org/verify/professional-cert/V854L4ZTTT2D
        image: /images/cert/gbi.png
      - title: Google Data Analytics
        content: May 2, 2023
        url: https://coursera.org/verify/professional-cert/MJGVBQSHTLBW
        image: /images/cert/gda.png
      - title: Google Digital Marketing & E-commerce
        content: June 9, 2023
        url: https://coursera.org/verify/professional-cert/DALSLQSJ9DLZ
        image: /images/cert/gdme.png
      - title: Meta Marketing Analytics
        content: June 8, 2023
        url: https://coursera.org/verify/professional-cert/3HJDGQC8ZSHN
        image: /images/cert/mma.png
      - title: Meta Social Media Marketing
        content: May 5, 2023
        url: https://coursera.org/verify/professional-cert/KRLUMUYSCBT8
        image: /images/cert/msmm.png

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-x-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # # title: "Custom Name"
    # content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    # btnName: Mail me
    # btnLink: mailto:gurusabarisha@gmail.com
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xqaardwj # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
