# --- SITE INFORMATION AND META DATA --- #
baseURL: "https://thelabdigital.github.io/"
languageCode: "en-us"
title: "Sithu Aung"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 3

enableRobotsTXT: true
# disqusShortname: sithuaung
googleAnalytics: G-EY3KH0WZKV

markup:
  goldmark:
    renderer:
      unsafe: true

# --- MAIN MENU ITEMS (EXPECT FROM ANCHOR POINT ON LANDING PAGE) --- #
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

params:
  title: "Sithu Aung"
  description: My Porfolio and blog
  favicon: "/fav.png"
  useBootstrapCDN: false
  mathjax: false
  animate: true
  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark
  font:
    fontSize: 1.15rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Sithu Aung" # Brand name for the brand | default is the title variable
    disableSearch: false
    searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Sithu Aung."
    subtitle: "I develop strategies, making yours simply work!"
    content: "Hi there! Your friendly neighborhood marketing strategist, analyst, consultant, research enthusiast, and—let's face it—a full-on strategy aficionado is here!"
    image: /images/me_hero_2.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Download My Resume"
      url: "/cv/STA_CV_2025_Jan.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-square-facebook
          url: https://www.facebook.com/sithu.aung.leo
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/sithuaung88/
        - icon: fab fa-github
          url: https://github.com/SithuAung1988

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me_hero_1.jpg"
    content: |-
              I'm a strategic marketing professional from Myanmar with a solid background in media, marketing, communication, and advertising. I began my career at 19 in Dubai's hospitality industry, transitioned to Myanmar's print media sector in 2010, and by 2016 was developing digital and social media strategies at "Ogilvy Myanmar". Later, I became "Head of Digital Sales and Marketing" at "The Irrawaddy Media", one of Myanmar's leading digital media outlets, and co-founded "The Lab Digital", an agency supporting local MSMEs and NGOs. I've also worked as a Consultant and freelanced for organizations of all sizes, including "[Hogarth Worldwide](https://www.hogarth.com)", "[ICAP at Columbia University](https://icap.columbia.edu)", and "[Institute for Strategy and Policy - Myanmar](https://ispmyanmar.com/)".

              Outside of work, I'm a reader, writer, blogger and online educator, teaching classes via Zoom on topics like business strategy, marketing, data analytics, and operational research to inspire Myanmar's next generation of marketers. In my free time, I enjoy coding for fun (Python, PHP, R, and SQL, if you're curious), exploring Buddhist ethics in business strategies, and geeking out on Indian/Hindu astrology. (Check out my GitHub to learn more about my Python project on Hindu astrology.) I'm also a lifelong Manchester United fan and a proud cat parent.

              Currently, I'm focused on enhancing my skills in developing and optimizing strategies, consumer behavior and marketing, and data analytics, AI in marketing, and business ethics. If you're looking for someone versatile, adaptable, and ready to make an impact, let's connect!
    skills:
      enable: true
      title: "Here are a few of the topics I'm currently working on:"
      items:
            - Strategy Development and Consultation
            - Marketing and Communication Campaigns
            - Performance Monitoring, Evaluation, and Optimization
            - Research and Data Analytics
            - Content Creation
            - Training

            # - Strategy Development and Consultation - including market entry strategies  
            # - Planning and Execution of Marketing and Communication Campaigns  
            # - Data Collection, Statistical Analysis, Data Interpretation, and Presentation  
            # - Development of Business Plans, Marketing Plans, Campaign Plans, and Project Proposals  
            # - Content Strategy, Content Creation, Copywriting, Translation, and Editing  
            # - Research and Training in Marketing  

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:

##### - Job #01 - #####
      - job: "Business Development Consultant"
        company: "The Lab Digital"
        companyUrl: "https://www.facebook.com/TheLabDigital"
        date: "Oct 2016 - Present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |-
          After I left my job at Ogilvy Myanmar, I wanted to utilize my skills in digital marketing and my connections in the marketing and communication industry. The Lab was founded by a small but very passionate group of professionals. So I joined there in 2016 as a non-payroll employee. My main responsibilities as Business Development Consultant there are :

          - Developing new business opportunities
          - Developing business proposals
          - Maintaining relationships with clients
          - Research and development

##### - Job #02 - #####
      - job: "Lead Content Developer - Burmese Language"
        company: "Hogarth Worldwide"
        companyUrl: "https://www.hogarth.com"
        date: "Jun 2022 - Present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |-
          After being awarded over a USD 4 bn worth world wide project from Coca-Cola in 2022, HogarthWW approached me to lead their content creation efforts for the Myanmar market and I joined there as a contractor. My main responsibilities there are:

          - Ensuring all Burmese contents are aligned with local culture and laws.
          - Ensuring all Burmese contents are properly developed, translated and aligned with client’s feedback.
          - Developing new content ideas to optimize the audience engagement.

##### - Job #03 - #####
      - job: "Content Consultant - English Edition"
        company: "ISP - Myanmar"
        companyUrl: "https://ispmyanmar.com/"
        date: "Jun 2020 - Mar 2023"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |-
          During Covid pandemic and after the Coup, ISP-Myanmar developed over 150 policy related articles and they wanted to translate them into English. They approached me to oversee their translation project and I joined there as a non-payroll consultant. My primary responsibilities there were:

          - Ensuring all translations were met with ISP-Myanmar standards and in-house content styles.
          - Ensuring all projects were met with their deadline.
          - Overseeing the Data Visualization process.

          My contract was terminated after successfully finishing the project.

##### - Job #04 - #####
      - job: "Digital Sales and Marketing Manager"
        company: "Irrawaddy Media"
        companyUrl: "https://www.irrawaddy.com/"
        date: "Sep 2017 - Jun 2020"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |-
          I joined The Irrawaddy in Sep 2017 as a digital sales and marketing officer. Back then my main responsibilities was to generate revenue from advertising. But six months later, I was promoted as a digital sales and marketing manager. Then my responsibilities were no longer limited to sell ads spaces and were extended to diversify The Irrawaddy’s revenue sources not only exploring new opportunities but also strengthening the existing ones. My primary responsibilities there were:

          - Assisting Win Thu, independent director back then and Sanjay Gathia, then project director - fundraising, to develop project proposals.
          - Maintaining communications and relationships with donors such as MDIF, NED and Partners Asia.
          - Tracking projects' activities and preparing reports.
          - Engaging different communities and organizations to explore new business opportunities.
          -  Researching and analyzing market trends and data such as PESTLE factors to develop new business opportunities and optimize existing ones.

          During Covid pandemic, the media industry was hit by the unprecedented downturn. The Irrawaddy was no longer able to afford my salary and I left the organization.

##### - Job #05 - #####
      - job: "Assistant Digital Planner"
        company: "Ogilvy Myanmar"
        companyUrl: "https://www.todayogilvy.com/"
        date: "Feb 2016 - Oct 2016"
        featuredLink:
          enable: false
          name: 
          url: 
        info:
          enable: false
          content: 
        content: |-
          After being awarded a contract from MPT, Ogilvy Myanmar was asked to develop digital 360 marketing and communication strategy for MPT. 
          They contacted Pete Mitchell, an ex-Ogilvian and founder of [Kudos Content](https://www.linkedin.com/company/kudos-content/about/), a Singapore based content marketing firm, to carry out the task. 
          After working over half of a decade in the media industry, I was hired to assist Pete for his MPT project. My primary responsibilities there were:

          - Acting as a liaison among Pete, Ogilvy internal teams and MPT.
          - Performing market research and analysis for Pete.
          - Developing various marcom strategies for each MPT's digital channels.
          - Researching Social@Ogilvy campaign database

          After MPT terminated its contract with Ogilvy, Pete's and my contracts were also terminated.

# Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      # --- MASTER DEGREE --- #
      - title: "Master of Marketing Management"
        school:
          name: "University of Economics, Monywa"
          url: "https://mue.edu.mm/"
        date: "2024 - Present"
        GPA: false
        content: |-
          Remark:
            - Right now, I'm enrolled in an online master's program in Marketing Management at the University of Economics, Monywa.
      # --- BACHELOR DEGREE --- #
      - title: "Bachelor of Business Management"
        school:
          name: "University of Distance Education, Yangon"
          url: "https://www.yude.edu.mm/"
        date: "2006 - 2024"
        GPA: false
        content: |-
          Remark:
          - I dropped out of university back in 2008 and headed abroad to work.
          - Fast forward to 2022, I decided to jump back in and finish what I started. By 2024, I finally earned my degree!
      # --- HIGH SCHOOL --- #
      - title: "High School"
        school:
          name: "Basic Education High School No. 6 Botataung, Yangon"
          url: "https://en.wikipedia.org/wiki/Basic_Education_High_School_No._6_Botataung"
        date: "1998 - 2004"
        content: |-

          - Yes, I'm a proud alumnus of St. Paul's English High School.
  
  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: Google Advanced Data Analytics
        content: May 16, 2023
        url: https://coursera.org/verify/professional-cert/CPLUU9C2Y3E4
        image: /images/cert/gada.png
      - title: Google Business Intelligence
        content: May 17, 2023
        url: https://coursera.org/verify/professional-cert/V854L4ZTTT2D
        image: /images/cert/gbi.png
      - title: Google Data Analytics
        content: May 2, 2023
        url: https://coursera.org/verify/professional-cert/MJGVBQSHTLBW
        image: /images/cert/gda.png
      - title: Google Digital Marketing & E-commerce
        content: June 9, 2023
        url: https://coursera.org/verify/professional-cert/DALSLQSJ9DLZ
        image: /images/cert/gdme.png
      - title: Meta Marketing Analytics
        content: June 8, 2023
        url: https://coursera.org/verify/professional-cert/3HJDGQC8ZSHN
        image: /images/cert/mma.png
      - title: Meta Social Media Marketing
        content: May 5, 2023
        url: https://coursera.org/verify/professional-cert/KRLUMUYSCBT8
        image: /images/cert/msmm.png

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Absolute Essentials of Strategic Marketing
        content: I wrote a book on strategic marketing in 2023, covering key topics like the 7Ps of marketing and the marketing funnel.
        image: /images/projects/book_marketing_tld_01.jpg
        featured:
          name: Grub your own copy, NOW!
          link: https://www.facebook.com/TheLabDigitalPublishing
        badges:
          - "Marketing"
          - "Strategic Marketing"
          - "Business Strategy"
        links:
          - icon: fab fa-facebook
            url: https://www.facebook.com/ESMBookbyKoSithu

      - title: Office Politics - Everything You Need To Know
        content: Back in 2019, I wrote a book on office politics. It covers common challenges, like handling difficult bosses and navigating tough negotiations.
        image: /images/projects/book_office_politics_tld_00.jpg
        featured:
          name: Grub your own copy, NOW!
          link: https://www.facebook.com/TheLabDigitalPublishing
        badges:
          - "Office Politics"
          - "Interpersonal Skills"
          - "EQ Skills"
          - "Emotional Intelligence"
        links:
          - icon: fab fa-facebook
            url: https://www.facebook.com/TheLabDigitalPublishing

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # # title: "Custom Name"
    # content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    # btnName: Mail me
    # btnLink: mailto:gurusabarisha@gmail.com
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: xqaardwj # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
